import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import Ajv2020 from 'ajv/dist/2020.js'
import addFormats from 'ajv-formats'
import { createElement, downloadDocument, fileCommand, loadDocument, noPageScroll, openModule, savedDocument } from './acceptance-helpers'

test('documento integrado: pines, estado, Cuaderno, JSON, Nuevo, carga y recarga', async ({ page }, info) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }))
  await page.goto('/')
  await expect(page.locator('[data-module]')).toHaveCount(0)
  await page.getByLabel('Título del documento').fill('Integración áé<>.JSON')
  for (const name of ['Pizarra', 'Elementos', 'Operativo', 'Cuaderno']) await openModule(page, name)
  await createElement(page, 'Tango integración', true)
  const surface = page.getByTestId('board-surface'), pin = page.locator('.board-pin-visual')
  const before = (await pin.boundingBox())!, square = (await surface.boundingBox())!
  await page.mouse.move(before.x + before.width / 2, before.y + before.height / 2)
  await page.mouse.down(); await page.waitForTimeout(280)
  await page.mouse.move(before.x + before.width / 2 - square.width * .15, before.y + before.height / 2 + square.height * .1, { steps: 8 })
  await page.mouse.up()
  await expect.poll(async () => (await savedDocument(page))?.elements[0]?.position?.x ?? 1000).toBeLessThan(400)
  const ops = page.getByRole('region', { name: 'Operativo', exact: true })
  await ops.getByRole('button', { name: 'En camino', exact: true }).click()
  await ops.getByLabel('Anotación').fill('Comprobar radio')
  await ops.getByRole('textbox', { name: 'Nueva etiqueta' }).fill('Sector norte')
  await ops.getByRole('textbox', { name: 'Nueva etiqueta' }).press('Enter')
  await createElement(page, 'Acceso integración', false, '📍')
  const notebook = page.getByRole('region', { name: 'Cuaderno', exact: true })
  await notebook.getByRole('button', { name: 'Añadir bloque' }).click()
  await page.getByRole('menuitem', { name: 'Nota', exact: true }).click()
  await notebook.getByLabel('Texto de nota').fill('Preparación\n📻 Revisar canal')
  const exported = await downloadDocument(page)
  expect(exported.download.suggestedFilename()).toBe('Integración áé.json')
  const ajv = new Ajv2020({ strict: true })
  addFormats(ajv)
  const schema = JSON.parse(await readFile('src/domain/document/schema/angie-document-v1.schema.json', 'utf8'))
  expect(ajv.compile(schema)(exported.document)).toBe(true)
  expect(Object.keys(exported.document)).toEqual(['format', 'formatVersion', 'document', 'board', 'elements', 'notebook', 'timeline', 'moduleLayouts', 'filters'])
  expect(exported.document.elements).toHaveLength(2)
  expect(exported.document.elements[0]?.operational).toEqual({ status: 'En camino', notes: 'Comprobar radio', tags: ['Sector norte'] })
  expect(exported.document.timeline).toHaveLength(1)
  expect(exported.text.endsWith('\n')).toBe(true)
  await expect.poll(async () => (await savedDocument(page))?.notebook).toEqual(exported.document.notebook)
  await fileCommand(page, 'Nuevo')
  await expect(notebook.getByLabel('Texto de nota')).toHaveCount(0)
  expect(await readFile((await exported.download.path())!, 'utf8')).toBe(exported.text)
  await loadDocument(page, exported.document)
  await expect(notebook.getByLabel('Texto de nota')).toHaveValue('Preparación\n📻 Revisar canal')
  await expect.poll(async () => (await savedDocument(page))?.elements).toEqual(exported.document.elements)
  await page.reload()
  await expect(page.locator('[data-module]')).toHaveCount(0)
  await expect(page.getByLabel('Título del documento')).toHaveValue('Integración áé<>.JSON')
  await openModule(page, 'Pizarra')
  await expect(page.getByRole('button', { name: 'Seleccionar Tango integración' })).toHaveAttribute('aria-pressed', 'false')
  await noPageScroll(page)
  await page.screenshot({ path: info.outputPath('document-recovered.png') })
  expect(errors).toEqual([])
})
