import { expect, test } from '@playwright/test'
import { createElement, downloadDocument, loadDocument, noPageScroll, openModule, savedDocument } from './acceptance-helpers'

test('sin red: documento, selección, estados, coordenadas, calculadora, Cuaderno y JSON', async ({ page, context }, info) => {
  const errors: string[] = [], external: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (new URL(request.url()).origin !== 'http://127.0.0.1:4173') external.push(request.url()) })
  await page.addInitScript(() => Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }))
  await page.goto('/')
  await page.waitForFunction(() => Boolean(navigator.serviceWorker.controller))
  await context.setOffline(true); await page.reload()
  await page.getByLabel('Título del documento').fill('Trabajo offline')
  await openModule(page, 'Elementos'); await createElement(page, 'Tango offline', true, '🚗')
  await openModule(page, 'Operativo')
  await page.getByRole('region', { name: 'Operativo', exact: true }).getByRole('button', { name: 'En destino', exact: true }).click()
  await page.getByRole('button', { name: 'Cerrar Elementos', exact: true }).click()
  await page.getByRole('button', { name: 'Cerrar Operativo', exact: true }).click()
  await openModule(page, 'Coordenadas')
  const coordinates = page.getByRole('region', { name: 'Coordenadas', exact: true })
  await coordinates.getByRole('textbox', { name: 'Coordenadas', exact: true }).fill('30S 588700 4101800')
  await coordinates.getByRole('button', { name: 'Convertir' }).press('Enter')
  await expect(coordinates.getByLabel('Resultado DD')).toHaveText(/^37\./)
  const link = new URL(await coordinates.getByLabel('Enlace de Google Maps').inputValue())
  expect(link.origin).toBe('https://www.google.com')
  expect(link.searchParams.get('query')).toMatch(/^37\.\d+,-2\./)
  await coordinates.getByRole('textbox', { name: 'Coordenadas', exact: true }).fill('30I 588700 4101800')
  await coordinates.getByRole('button', { name: 'Convertir' }).press('Enter')
  await expect(coordinates.getByRole('alert')).toBeVisible()
  await expect(coordinates.getByRole('textbox', { name: 'Coordenadas', exact: true })).toHaveValue('30I 588700 4101800')
  await expect(coordinates.getByLabel('Enlace de Google Maps')).toHaveCount(0)
  await page.getByRole('button', { name: 'Cerrar Coordenadas', exact: true }).click()
  await openModule(page, 'Calculadora')
  const calculator = page.getByRole('region', { name: 'Calculadora', exact: true })
  await calculator.getByLabel('Operación').fill('80 + 12,5 %')
  await calculator.getByLabel('Operación').press('Enter')
  await expect(calculator.getByLabel('Resultado', { exact: true })).toHaveText('90')
  await page.getByRole('button', { name: 'Cerrar Calculadora', exact: true }).click()
  await openModule(page, 'Cuaderno')
  const notebook = page.getByRole('region', { name: 'Cuaderno', exact: true })
  await notebook.getByRole('button', { name: 'Añadir bloque' }).click()
  await page.getByRole('menuitem', { name: 'Checklist' }).click()
  await notebook.getByRole('button', { name: 'Añadir elemento' }).click()
  await notebook.getByLabel('Texto del elemento 1').fill('Revisar radio 📻')
  await notebook.getByRole('checkbox', { name: 'Marcar elemento 1' }).check()
  const exported = await downloadDocument(page)
  expect(exported.document.elements[0]?.operational?.status).toBe('En destino')
  expect(exported.document.timeline).toHaveLength(1)
  expect(exported.document.notebook[0]).toMatchObject({ type: 'checklist', items: [{ text: 'Revisar radio 📻', checked: true }] })
  await loadDocument(page, exported.document)
  await expect.poll(async () => (await savedDocument(page))?.notebook).toEqual(exported.document.notebook)
  await page.reload(); await expect(page.locator('[data-module]')).toHaveCount(0)
  await openModule(page, 'Cuaderno')
  await expect(notebook.getByRole('checkbox', { name: 'Marcar elemento 1' })).toBeChecked()
  await noPageScroll(page)
  await page.screenshot({ path: info.outputPath('offline-notebook.png') })
  expect(errors).toEqual([]); expect(external).toEqual([])
})
