import { expect, test } from '@playwright/test'
import { createEmptyDocument } from '../../src/domain/document/defaultDocument'
import { bringModuleToFront, createElement, loadDocument, openModule, savedDocument } from './acceptance-helpers'

test('estados libres, selección compartida, historial cerrado y corrección por dotación', async ({ page }) => {
  await page.goto('/')
  const document = createEmptyDocument('Aceptación operativa')
  document.moduleLayouts = { elements: { x: 0, y: 0, width: 300, height: 420, referenceSize: { width: 1600, height: 1000 } }, information: { x: 300, y: 0, width: 320, height: 240, referenceSize: { width: 1600, height: 1000 } }, operations: { x: 620, y: 0, width: 340, height: 320, referenceSize: { width: 1600, height: 1000 } }, timeline: { x: 960, y: 0, width: 420, height: 320, referenceSize: { width: 1600, height: 1000 } } }
  await loadDocument(page, document)
  for (const name of ['Dotaciones', 'Información', 'Operativo']) await openModule(page, name)
  await createElement(page, 'Tango A', true)
  await createElement(page, 'Tango B', true)
  const elements = page.getByRole('region', { name: 'Dotaciones', exact: true })
  const information = page.getByRole('region', { name: 'Información', exact: true })
  const ops = page.getByRole('region', { name: 'Operativo', exact: true })
  await elements.getByRole('button', { name: 'Seleccionar Tango A' }).press('Enter')
  await ops.getByRole('button', { name: 'Inoperativa', exact: true }).press('Enter')
  await ops.getByRole('button', { name: 'Activada', exact: true }).press('Enter')
  await expect(information.getByText('Alarma', { exact: true })).toBeVisible()
  await elements.getByRole('button', { name: 'Seleccionar Tango B' }).press('Enter')
  await ops.getByRole('button', { name: 'Operativa', exact: true }).press('Enter')
  await expect.poll(async () => (await savedDocument(page))?.timeline.length).toBe(3)
  await expect(page.locator('[data-module="timeline"]')).toHaveCount(0)
  await openModule(page, 'Registro cronológico')
  const timeline = page.getByRole('region', { name: 'Registro cronológico', exact: true })
  await expect(timeline.locator('li[data-current="true"]')).toHaveCount(2)
  await timeline.locator('li').filter({ hasText: 'Inoperativa ⚫ → Activada 🟡' }).getByRole('button', { name: 'Editar entrada' }).press('Enter')
  await timeline.getByRole('button', { name: 'Corregir estado actual' }).press('Enter')
  await page.getByRole('alertdialog').getByRole('button', { name: 'Confirmar corrección' }).press('Enter')
  await expect.poll(async () => (await savedDocument(page))?.elements[0]?.operational?.status).toBeNull()
  await expect.poll(async () => (await savedDocument(page))?.elements.map(item => item.operational?.status)).toEqual([null, 'Operativa'])
  await bringModuleToFront(page, 'Dotaciones')
  await elements.locator('.element-row[data-selected="true"]').getByRole('button', { name: 'Quitar', exact: true }).click()
  await expect(timeline.getByText(/Tango B/)).toBeVisible()
  await expect(timeline.locator('li[data-current="true"]')).toHaveCount(0)
})
