import { expect, test } from '@playwright/test'
import { downloadDocument, fileCommand, loadDocument, openModule } from './acceptance-helpers'

test('temporizadores independientes del documento, cierre de módulo, recarga y suspensión simulada', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }))
  await page.goto('/')
  await openModule(page, 'Reloj')
  await page.clock.install({ time: new Date('2026-10-01T12:00:00Z') })
  await page.clock.pauseAt(new Date('2026-10-01T12:00:01Z'))
  const clock = page.getByRole('region', { name: 'Reloj', exact: true })
  await clock.getByRole('button', { name: 'T-Zero', exact: true }).press('Enter')
  const zero = clock.getByRole('group', { name: 'T-Zero 1', exact: true })
  await zero.getByLabel('Nota', { exact: true }).fill('Tiempo independiente')
  await zero.getByRole('button', { name: 'Iniciar', exact: true }).press('Enter')
  await clock.getByRole('button', { name: 'T-Minus', exact: true }).press('Enter')
  const minus = clock.getByRole('group', { name: 'T-Minus 1', exact: true })
  await minus.getByLabel('Segundos', { exact: true }).fill('30')
  await minus.getByRole('button', { name: 'Iniciar', exact: true }).press('Enter')
  const exported = await downloadDocument(page)
  expect(exported.text).not.toContain('Tiempo independiente')
  await fileCommand(page, 'Nuevo')
  await loadDocument(page, exported.document)
  await expect(zero).toHaveAccessibleDescription('En marcha')
  await page.getByRole('button', { name: 'Cerrar Reloj', exact: true }).press('Enter')
  await page.clock.setSystemTime(new Date('2026-10-01T12:00:41Z'))
  await page.evaluate(() => document.dispatchEvent(new Event('visibilitychange')))
  await openModule(page, 'Reloj')
  await expect(zero.getByLabel('Tiempo', { exact: true })).toHaveText('00:00:40')
  await expect(minus).toHaveAttribute('data-alert', 'true')
  await minus.getByRole('button', { name: 'Reconocer alerta', exact: true }).press('Enter')
  await expect(minus).toHaveAccessibleDescription('Finalizado')
  await zero.getByRole('button', { name: 'Pausar', exact: true }).press('Enter')
  await page.clock.runFor(100)
  await page.reload()
  await expect(page.locator('[data-module]')).toHaveCount(0)
  await openModule(page, 'Reloj')
  await expect(zero.getByLabel('Nota', { exact: true })).toHaveValue('Tiempo independiente')
  await expect(zero.getByLabel('Tiempo', { exact: true })).toHaveText('00:00:40')
  await expect(minus).toHaveAccessibleDescription('Finalizado')
})
