import { act, fireEvent, render, renderHook, screen } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { useValidationNotice } from './useValidationNotice'
import { TooltipProvider } from './tooltip'
import { CoordinatesModule } from '../../features/coordinates/CoordinatesModule'
import { CalculatorModule } from '../../features/calculator/CalculatorModule'
import { ElementEditor } from '../../features/elements/ElementEditor'

afterEach(() => vi.useRealTimers())
describe('avisos de validación de fase 4', () => {
  it('una generación nueva retira aviso/resaltado y limpia su timer sin aceptar el dato', () => {
    vi.useFakeTimers()
    const view = render(<CalculatorModule generation={1} />)
    fireEvent.change(screen.getByRole('textbox', { name: 'Operación' }), { target: { value: '1/0' } })
    fireEvent.click(screen.getByRole('button', { name: 'Calcular' }))
    view.rerender(<CalculatorModule generation={2} />)
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Operación' })).toHaveValue('1/0')
    expect(screen.getByRole('textbox', { name: 'Operación' })).toHaveAttribute('aria-invalid', 'false')
    expect(vi.getTimerCount()).toBe(0)
    fireEvent.click(screen.getByRole('button', { name: 'Calcular' }))
    expect(screen.getByRole('alert')).toHaveTextContent('División por cero')
  })
  it('caduca a 5000 ms, repetir el mismo error reinicia el plazo y desmontar limpia el timer', () => {
    vi.useFakeTimers()
    const { result, unmount } = renderHook(() => useValidationNotice())
    act(() => result.current[1]('Inválido'))
    act(() => vi.advanceTimersByTime(4999))
    expect(result.current[0]).toBe('Inválido')
    act(() => result.current[1]('Inválido'))
    act(() => vi.advanceTimersByTime(4999))
    expect(result.current[0]).toBe('Inválido')
    act(() => vi.advanceTimersByTime(1))
    expect(result.current[0]).toBeNull()
    act(() => result.current[1]('Otro'))
    unmount()
    expect(vi.getTimerCount()).toBe(0)
  })
  it('Coordenadas retira aviso y resaltado sin convertir ni habilitar copia', () => {
    vi.useFakeTimers(); render(<CoordinatesModule />, { wrapper: TooltipProvider })
    const input = screen.getByRole('textbox', { name: 'Coordenadas' })
    fireEvent.change(input, { target: { value: '30I 588700 4101800' } })
    fireEvent.click(screen.getByRole('button', { name: 'Validar coordenadas y mostrar formatos' }))
    act(() => vi.advanceTimersByTime(4999))
    expect(input).toHaveAttribute('aria-invalid', 'true')
    expect(screen.getByRole('alert')).toBeVisible()
    act(() => vi.advanceTimersByTime(1))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(input).toHaveAttribute('aria-invalid', 'false')
    expect(input).not.toHaveAttribute('aria-describedby')
    expect(input).toHaveValue('30I 588700 4101800')
    expect(screen.queryByRole('button', { name: /^Copiar / })).not.toBeInTheDocument()
    expect(screen.getByLabelText('Resultado DD')).toBeEmptyDOMElement()
  })
  it('Calculadora conserva operación inválida sin resultado al expirar; reintentar muestra el error', () => {
    vi.useFakeTimers(); render(<CalculatorModule />)
    fireEvent.change(screen.getByRole('textbox', { name: 'Operación' }), { target: { value: '1/0' } })
    fireEvent.click(screen.getByRole('button', { name: 'Calcular' }))
    act(() => vi.advanceTimersByTime(5000))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Operación' })).toHaveValue('1/0')
    expect(screen.getByLabelText('Resultado')).toBeEmptyDOMElement()
    fireEvent.click(screen.getByRole('button', { name: 'Calcular' }))
    expect(screen.getByRole('alert')).toHaveTextContent('División por cero')
  })
  it('editor vacío no crea al expirar ni pierde borrador', () => {
    vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} })
    vi.useFakeTimers(); const save = vi.fn()
    render(<ElementEditor onSave={save} onCancel={() => {}} />)
    fireEvent.click(screen.getByRole('button', { name: 'Crear' }))
    expect(screen.getByRole('alert')).toBeVisible()
    expect(screen.getByRole('textbox', { name: 'Nombre' })).toHaveAttribute('aria-invalid', 'true')
    expect(screen.getByRole('textbox', { name: 'Nombre' })).toHaveAccessibleDescription(screen.getByRole('alert').textContent!)
    act(() => vi.advanceTimersByTime(5000))
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('textbox', { name: 'Nombre' })).toHaveAttribute('aria-invalid', 'false')
    expect(save).not.toHaveBeenCalled()
    expect(screen.getByRole('textbox', { name: 'Nombre' })).toHaveValue('')
  })
})
